### ISSUE TITLE
Deprecation Message for Resolver

### ISSUE THREAD

**Issue by NateDawg90** [pswai/ember-cli-react#3]
I'm using the library and it's working well so far though I'm still working through upgrade bugs and deprecations.

On Ember v3.16, they started deprecating the globals resolver. Instead, they want you to extend from ember-cli-resolver. I believe the package currently imports from ember-resolver, when it should be ember-cli-resolver.. 

https://deprecations.emberjs.com/v3.x/#toc_ember-deprecate-globals-resolver

**Comment by pswai** [comment]
@NateDawg90 Yes I noticed the deprecation messages as well and is going to work on them. So far I have tested v3.16 and it is still working fine even with Octane (angled bracket components, etc).

I will try to make sure this addon supports up to 3.28 without deprecation warnings. If you would like to submit PRs that's very welcomed too :D 

Side note: For ember-cli-resolver, initially i thought it's a different addon too. Turns out it is the ember-resolver package. 😅

**Comment by NateDawg90** [comment]
Thanks, I'll be sure to submit a PR if I find anything obvious. 

Could you also include a link to the NPM page for the package somewhere convenient?

**Comment by pswai** [comment]
@NateDawg90 Sorry I was pretty busy for the past few days. Going to pick this up again this weekend. Which package are you referring to?

**Comment by NateDawg90** [comment]
Just referring to the NPM page for the forked package. I had to search manually on NPM: https://www.npmjs.com/package/ember-cli-react-fork

**Comment by pswai** [comment]
@NateDawg90 Right i'll update it in the Readme later.

By the way for the deprecation message, do you still encounter it? Over the weekend I have tried upgrading a test repo from Ember 3.4 to 3.28 in a LTS by LTS fashion. Things seem to be working fine. I did encounter the resolver deprecation message but it is solved once I updated `app.js` like this:
```js
// From this
import Resolver from './resolver';

// To this
import Resolver from 'ember-cli-react/resolver';
```

The deprecation message then disappears. Can you see if this works?

**Comment by NateDawg90** [comment]
I'm on Ember 3.24 now and ember-cli-react-fork 2.0.1, , and my App.js looks like this:

`import Application from '@ember/application';
import Resolver from 'ember-cli-react/resolver';
import loadInitializers from 'ember-load-initializers';
import config from 'bitfusion/config/environment';

export default class App extends Application {
  modulePrefix = config.modulePrefix;
  podModulePrefix = config.podModulePrefix;
  Resolver = Resolver;
}

loadInitializers(App, config.modulePrefix);
`

I'm still seeing the deprecation message. There are 3 of them to be exact:
<img width="476" alt="Screen Shot 2021-09-27 at 11 24 10 AM" src="https://user-images.githubusercontent.com/18134083/134938919-90781d1c-9f7e-4ac1-aa7f-2037d8db8ce5.png">
<img width="462" alt="Screen Shot 2021-09-27 at 11 24 05 AM" src="https://user-images.githubusercontent.com/18134083/134938923-e41be868-76da-48a7-b0b7-a52e3df2cd98.png">
<img width="456" alt="Screen Shot 2021-09-27 at 11 23 59 AM" src="https://user-images.githubusercontent.com/18134083/134938926-78757a9b-ddf8-41a7-b536-7e5954ce1e04.png">

**Comment by NateDawg90** [comment]
Resolving this. I discovered it was from another library I had in my package.json called "ember-cli-shims". It wasn't being depended on by anything else or used anywhere, so I removed it, and the dep warnings left with it. Thanks!

**Comment by pswai** [comment]
@NateDawg90 That's great to hear 👍
